name: Validate PR
run-name: 🚀 ${{ github.actor }} is validating PR ${{ github.event.number }}

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm i --global yarn
        run: yarn
      - name: Tests
        run: yarn test
